FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci


FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=dependencies \
    /app/node_modules \
    ./node_modules

COPY . .

ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder \
    /app/package.json \
    ./package.json

COPY --from=builder \
    /app/package-lock.json \
    ./package-lock.json

COPY --from=builder \
    /app/node_modules \
    ./node_modules

COPY --from=builder \
    /app/.next \
    ./.next

COPY --from=builder \
    /app/public \
    ./public

EXPOSE 3000

CMD ["npm", "run", "start"]