"""add usage quotas and llm usage events

Revision ID: 33e3a2796070
Revises: 05475f6036de
Create Date: 2026-08-24 11:26:31.077320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e3a2796070'
down_revision: Union[str, Sequence[str], None] = '05475f6036de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_limit',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('chat_channel_id', sa.UUID(), nullable=True),
    sa.Column('daily_message_limit', sa.Integer(), nullable=True),
    sa.Column('daily_input_token_limit', sa.Integer(), nullable=True),
    sa.Column('daily_output_token_limit', sa.Integer(), nullable=True),
    sa.Column('daily_total_token_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_message_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_input_token_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_output_token_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_total_token_limit', sa.Integer(), nullable=True),
    sa.Column('max_input_tokens_per_request', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens_per_request', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(knowledge_base_id IS NULL AND chat_channel_id IS NULL) OR (knowledge_base_id IS NOT NULL AND chat_channel_id IS NULL) OR (knowledge_base_id IS NOT NULL AND chat_channel_id IS NOT NULL)', name='ck_usage_limit_scope'),
    sa.ForeignKeyConstraint(['chat_channel_id'], ['chat_channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_limit_chat_channel_id'), 'usage_limit', ['chat_channel_id'], unique=False)
    op.create_index(op.f('ix_usage_limit_knowledge_base_id'), 'usage_limit', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_usage_limit_tenant_id'), 'usage_limit', ['tenant_id'], unique=False)
    op.create_index('uq_usage_limit_channel_scope', 'usage_limit', ['chat_channel_id'], unique=True, postgresql_where=sa.text('chat_channel_id IS NOT NULL'))
    op.create_index('uq_usage_limit_kb_scope', 'usage_limit', ['knowledge_base_id'], unique=True, postgresql_where=sa.text('knowledge_base_id IS NOT NULL AND chat_channel_id IS NULL'))
    op.create_index('uq_usage_limit_tenant_scope', 'usage_limit', ['tenant_id'], unique=True, postgresql_where=sa.text('knowledge_base_id IS NULL AND chat_channel_id IS NULL'))
    op.create_table('llm_usage_event',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('chat_channel_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.String(length=50), server_default='chat', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_channel_id'], ['chat_channel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_event_chat_channel_id'), 'llm_usage_event', ['chat_channel_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_conversation_id'), 'llm_usage_event', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_knowledge_base_id'), 'llm_usage_event', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_message_id'), 'llm_usage_event', ['message_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_model'), 'llm_usage_event', ['model'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_provider'), 'llm_usage_event', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_request_type'), 'llm_usage_event', ['request_type'], unique=False)
    op.create_index(op.f('ix_llm_usage_event_tenant_id'), 'llm_usage_event', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_event_tenant_id'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_request_type'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_provider'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_model'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_message_id'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_knowledge_base_id'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_conversation_id'), table_name='llm_usage_event')
    op.drop_index(op.f('ix_llm_usage_event_chat_channel_id'), table_name='llm_usage_event')
    op.drop_table('llm_usage_event')
    op.drop_index('uq_usage_limit_tenant_scope', table_name='usage_limit', postgresql_where=sa.text('knowledge_base_id IS NULL AND chat_channel_id IS NULL'))
    op.drop_index('uq_usage_limit_kb_scope', table_name='usage_limit', postgresql_where=sa.text('knowledge_base_id IS NOT NULL AND chat_channel_id IS NULL'))
    op.drop_index('uq_usage_limit_channel_scope', table_name='usage_limit', postgresql_where=sa.text('chat_channel_id IS NOT NULL'))
    op.drop_index(op.f('ix_usage_limit_tenant_id'), table_name='usage_limit')
    op.drop_index(op.f('ix_usage_limit_knowledge_base_id'), table_name='usage_limit')
    op.drop_index(op.f('ix_usage_limit_chat_channel_id'), table_name='usage_limit')
    op.drop_table('usage_limit')
    # ### end Alembic commands ###
