"""create knowledge_base table

Revision ID: 4ac58c312e8d
Revises: 367f4d133071
Create Date: 2026-08-10 12:05:59.287596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac58c312e8d'
down_revision: Union[str, Sequence[str], None] = '367f4d133071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='knowledgebasestatus'), server_default='ACTIVE', nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SHARED', name='knowledgebasevisibility'), server_default='PRIVATE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_owner_user_id'), 'knowledge_base', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_tenant_id'), 'knowledge_base', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_tenant_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_owner_user_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
