"""add integration and tool registry

Revision ID: 543c2c59fa94
Revises: 9728a0b9cce0
Create Date: 2026-08-17 14:00:19.027458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543c2c59fa94'
down_revision: Union[str, Sequence[str], None] = '9728a0b9cce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('integration_type', sa.Enum('REST', 'MCP', name='integrationtype'), nullable=False),
    sa.Column('base_url', sa.String(length=2000), nullable=False),
    sa.Column('auth_type', sa.Enum('NONE', 'BEARER', 'API_KEY', name='integrationauthtype'), server_default='NONE', nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_integration_type'), 'integration', ['integration_type'], unique=False)
    op.create_index(op.f('ix_integration_tenant_id'), 'integration', ['tenant_id'], unique=False)
    op.create_table('tool_definition',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.Enum('NATIVE', 'REST', 'MCP', name='tooltype'), nullable=False),
    sa.Column('risk_level', sa.Enum('READ', 'WRITE', name='toolrisklevel'), server_default='READ', nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_definition_integration_id'), 'tool_definition', ['integration_id'], unique=False)
    op.create_index(op.f('ix_tool_definition_tenant_id'), 'tool_definition', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_definition_tool_type'), 'tool_definition', ['tool_type'], unique=False)
    op.create_table('agent_tool',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_id', name='uq_agent_tool')
    )
    op.create_index(op.f('ix_agent_tool_agent_id'), 'agent_tool', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_tool_id'), 'agent_tool', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tool_tool_id'), table_name='agent_tool')
    op.drop_index(op.f('ix_agent_tool_agent_id'), table_name='agent_tool')
    op.drop_table('agent_tool')
    op.drop_index(op.f('ix_tool_definition_tool_type'), table_name='tool_definition')
    op.drop_index(op.f('ix_tool_definition_tenant_id'), table_name='tool_definition')
    op.drop_index(op.f('ix_tool_definition_integration_id'), table_name='tool_definition')
    op.drop_table('tool_definition')
    op.drop_index(op.f('ix_integration_tenant_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_integration_type'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
