"""add slack channel credentials

Revision ID: 5676e9639baa
Revises: 6d48afd9e861
Create Date: 2026-08-22 11:02:31.232442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5676e9639baa'
down_revision: Union[str, Sequence[str], None] = '6d48afd9e861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_channel_slack_credential',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_name', sa.String(length=255), nullable=True),
    sa.Column('bot_user_id', sa.String(length=64), nullable=True),
    sa.Column('bot_token', sa.String(length=2048), nullable=False),
    sa.Column('signing_secret', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_channel_slack_credential_channel_id'), 'chat_channel_slack_credential', ['channel_id'], unique=True)
    op.create_index(op.f('ix_chat_channel_slack_credential_slack_team_id'), 'chat_channel_slack_credential', ['slack_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_channel_slack_credential_slack_team_id'), table_name='chat_channel_slack_credential')
    op.drop_index(op.f('ix_chat_channel_slack_credential_channel_id'), table_name='chat_channel_slack_credential')
    op.drop_table('chat_channel_slack_credential')
    # ### end Alembic commands ###
