"""add agent run tracing

Revision ID: 9728a0b9cce0
Revises: e2f68f203fa1
Create Date: 2026-08-16 20:29:33.115081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9728a0b9cce0'
down_revision: Union[str, Sequence[str], None] = 'e2f68f203fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus'), server_default='RUNNING', nullable=False),
    sa.Column('llm_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_agent_id'), 'agent_run', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_run_status'), 'agent_run', ['status'], unique=False)
    op.create_index(op.f('ix_agent_run_tenant_id'), 'agent_run', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_run_user_id'), 'agent_run', ['user_id'], unique=False)
    op.create_table('agent_run_step',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('LLM', 'TOOL', name='agentrunsteptype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='agentrunstepstatus'), server_default='COMPLETED', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_step_run_id'), 'agent_run_step', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_step_run_id'), table_name='agent_run_step')
    op.drop_table('agent_run_step')
    op.drop_index(op.f('ix_agent_run_user_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_tenant_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_status'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_agent_id'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
