"""add user knowledge base access

Revision ID: 9aaa41060ed2
Revises: a50cfec69b1d
Create Date: 2026-08-13 13:53:48.038384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa41060ed2'
down_revision: Union[str, Sequence[str], None] = 'a50cfec69b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_knowledge_base_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'MANAGE', name='knowledgebaseaccesslevel'), server_default='READ', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_base_id', name='uq_user_knowledge_base_access')
    )
    op.create_index(op.f('ix_user_knowledge_base_access_knowledge_base_id'), 'user_knowledge_base_access', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_user_knowledge_base_access_user_id'), 'user_knowledge_base_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_knowledge_base_access_user_id'), table_name='user_knowledge_base_access')
    op.drop_index(op.f('ix_user_knowledge_base_access_knowledge_base_id'), table_name='user_knowledge_base_access')
    op.drop_table('user_knowledge_base_access')
    # ### end Alembic commands ###
