"""add llm model pricing

Revision ID: b3e12abf6c86
Revises: 91425c0044ea
Create Date: 2026-09-01 18:47:32.470606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e12abf6c86'
down_revision: Union[str, Sequence[str], None] = '91425c0044ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_model_pricing',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('pricing_method', sa.String(length=50), server_default='token', nullable=False),
    sa.Column('input_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('unit_quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pricing_version', sa.String(length=100), nullable=True),
    sa.Column('pricing_source', sa.String(length=255), nullable=True),
    sa.Column('pricing_metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_model_pricing_effective_from'), 'llm_model_pricing', ['effective_from'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_effective_to'), 'llm_model_pricing', ['effective_to'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_is_active'), 'llm_model_pricing', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_model'), 'llm_model_pricing', ['model'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_pricing_method'), 'llm_model_pricing', ['pricing_method'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_provider'), 'llm_model_pricing', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_model_pricing_tenant_id'), 'llm_model_pricing', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_model_pricing_tenant_id'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_provider'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_pricing_method'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_model'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_is_active'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_effective_to'), table_name='llm_model_pricing')
    op.drop_index(op.f('ix_llm_model_pricing_effective_from'), table_name='llm_model_pricing')
    op.drop_table('llm_model_pricing')
    # ### end Alembic commands ###
