"""create knowledge_source table

Revision ID: c2f3819fef58
Revises: 4ac58c312e8d
Create Date: 2026-08-10 16:57:37.586052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f3819fef58'
down_revision: Union[str, Sequence[str], None] = '4ac58c312e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_source',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('UPLOAD', 'WEBSITE', 'SHAREPOINT', 'CONFLUENCE', 'GITHUB', 'GOOGLE_DRIVE', 'ONEDRIVE', 'S3', name='knowledgesourcetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='knowledgesourcestatus'), server_default='ACTIVE', nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_source_created_by'), 'knowledge_source', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_source_knowledge_base_id'), 'knowledge_source', ['knowledge_base_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_source_knowledge_base_id'), table_name='knowledge_source')
    op.drop_index(op.f('ix_knowledge_source_created_by'), table_name='knowledge_source')
    op.drop_table('knowledge_source')
    # ### end Alembic commands ###
