"""create document table

Revision ID: c6baec27189f
Revises: c2f3819fef58
Create Date: 2026-08-10 17:39:20.577284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6baec27189f'
down_revision: Union[str, Sequence[str], None] = 'c2f3819fef58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='documentstatus'), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_source.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_document_checksum'), 'document', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_external_id'), 'document', ['external_id'], unique=False)
    op.create_index(op.f('ix_document_knowledge_source_id'), 'document', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_document_uploaded_by'), 'document', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_uploaded_by'), table_name='document')
    op.drop_index(op.f('ix_document_knowledge_source_id'), table_name='document')
    op.drop_index(op.f('ix_document_external_id'), table_name='document')
    op.drop_index(op.f('ix_document_checksum'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
