"""add chat channels

Revision ID: c7d39e32c6b5
Revises: c82f6a1d3e20
Create Date: 2026-08-21 14:56:28.298121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d39e32c6b5'
down_revision: Union[str, Sequence[str], None] = 'c82f6a1d3e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_channel',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC_API', 'WEBSITE', 'SLACK', 'TEAMS', name='chatchanneltype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='chatchannelstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_channel_knowledge_base_id'), 'chat_channel', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_chat_channel_status'), 'chat_channel', ['status'], unique=False)
    op.create_index(op.f('ix_chat_channel_tenant_id'), 'chat_channel', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_channel_type'), 'chat_channel', ['type'], unique=False)
    op.create_table('chat_channel_api_key',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_channel_api_key_channel_id'), 'chat_channel_api_key', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_channel_api_key_key_hash'), 'chat_channel_api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_chat_channel_api_key_key_prefix'), 'chat_channel_api_key', ['key_prefix'], unique=False)
    op.drop_index(op.f('ix_document_ingestion_job_queue'), table_name='document_ingestion_job')
    op.drop_index(op.f('uq_document_ingestion_job_active_document'), table_name='document_ingestion_job', postgresql_where="(status = ANY (ARRAY['PENDING'::documentingestionjobstatus, 'PROCESSING'::documentingestionjobstatus]))")
    op.drop_index(op.f('ix_knowledge_source_sync_history'), table_name='knowledge_source_sync')
    op.drop_index(op.f('ix_knowledge_source_sync_source'), table_name='knowledge_source_sync')
    op.drop_index(op.f('uq_knowledge_source_sync_active_source'), table_name='knowledge_source_sync', postgresql_where="(status = ANY (ARRAY['PENDING'::knowledgesourcesyncstatus, 'RUNNING'::knowledgesourcesyncstatus]))")
    op.create_index(op.f('ix_knowledge_source_sync_knowledge_source_id'), 'knowledge_source_sync', ['knowledge_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_source_sync_knowledge_source_id'), table_name='knowledge_source_sync')
    op.create_index(op.f('uq_knowledge_source_sync_active_source'), 'knowledge_source_sync', ['knowledge_source_id'], unique=True, postgresql_where="(status = ANY (ARRAY['PENDING'::knowledgesourcesyncstatus, 'RUNNING'::knowledgesourcesyncstatus]))")
    op.create_index(op.f('ix_knowledge_source_sync_source'), 'knowledge_source_sync', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_source_sync_history'), 'knowledge_source_sync', ['knowledge_source_id', 'created_at'], unique=False)
    op.create_index(op.f('uq_document_ingestion_job_active_document'), 'document_ingestion_job', ['document_id'], unique=True, postgresql_where="(status = ANY (ARRAY['PENDING'::documentingestionjobstatus, 'PROCESSING'::documentingestionjobstatus]))")
    op.create_index(op.f('ix_document_ingestion_job_queue'), 'document_ingestion_job', ['status', 'available_at', 'created_at'], unique=False)
    op.drop_index(op.f('ix_chat_channel_api_key_key_prefix'), table_name='chat_channel_api_key')
    op.drop_index(op.f('ix_chat_channel_api_key_key_hash'), table_name='chat_channel_api_key')
    op.drop_index(op.f('ix_chat_channel_api_key_channel_id'), table_name='chat_channel_api_key')
    op.drop_table('chat_channel_api_key')
    op.drop_index(op.f('ix_chat_channel_type'), table_name='chat_channel')
    op.drop_index(op.f('ix_chat_channel_tenant_id'), table_name='chat_channel')
    op.drop_index(op.f('ix_chat_channel_status'), table_name='chat_channel')
    op.drop_index(op.f('ix_chat_channel_knowledge_base_id'), table_name='chat_channel')
    op.drop_table('chat_channel')
    # ### end Alembic commands ###
