"""add agent foundation

Revision ID: e2f68f203fa1
Revises: a59a2d50ee3b
Create Date: 2026-08-16 19:23:16.305672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f68f203fa1'
down_revision: Union[str, Sequence[str], None] = 'a59a2d50ee3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('llm_configuration_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), server_default='6', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='agentstatus'), server_default='DRAFT', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['llm_configuration_id'], ['tenant_llm_configuration.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_created_by'), 'agent', ['created_by'], unique=False)
    op.create_index(op.f('ix_agent_llm_configuration_id'), 'agent', ['llm_configuration_id'], unique=False)
    op.create_index(op.f('ix_agent_tenant_id'), 'agent', ['tenant_id'], unique=False)
    op.create_table('agent_knowledge_base',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'knowledge_base_id', name='uq_agent_knowledge_base')
    )
    op.create_index(op.f('ix_agent_knowledge_base_agent_id'), 'agent_knowledge_base', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_base_knowledge_base_id'), 'agent_knowledge_base', ['knowledge_base_id'], unique=False)
    op.drop_constraint(op.f('fk_knowledge_base_llm_configuration'), 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_base', 'tenant_llm_configuration', ['llm_configuration_id'], ['id'])
    op.drop_index(op.f('uq_tenant_llm_configuration_default'), table_name='tenant_llm_configuration', postgresql_where='(is_default = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_tenant_llm_configuration_default'), 'tenant_llm_configuration', ['tenant_id'], unique=True, postgresql_where='(is_default = true)')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(op.f('fk_knowledge_base_llm_configuration'), 'knowledge_base', 'tenant_llm_configuration', ['llm_configuration_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_agent_knowledge_base_knowledge_base_id'), table_name='agent_knowledge_base')
    op.drop_index(op.f('ix_agent_knowledge_base_agent_id'), table_name='agent_knowledge_base')
    op.drop_table('agent_knowledge_base')
    op.drop_index(op.f('ix_agent_tenant_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_llm_configuration_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_created_by'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
