"""create tenant llm configuration

Revision ID: e5278053505b
Revises: ad5ab2d42b2a
Create Date: 2026-08-11 15:59:48.449341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5278053505b'
down_revision: Union[str, Sequence[str], None] = 'ad5ab2d42b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_llm_configuration',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GOOGLE', 'VLLM', 'OLLAMA', name='llmprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('api_key', sa.String(length=1000), nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0',nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='2048', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_llm_configuration_tenant_id'), 'tenant_llm_configuration', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_llm_configuration_tenant_id'), table_name='tenant_llm_configuration')
    op.drop_table('tenant_llm_configuration')
    # ### end Alembic commands ###
